version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "80:3000"
    depends_on:
      - server
    restart: unless-stopped
